<?php 

require_once '../../../basefunction/database_connection.php';

//if form is submitted
if($_POST) {	

	$validator = array('success' => false, 'messages' => array());
	$BOOKING_ID = $_POST['BOOKING_ID'];
	$BOOKING_PSENDER = $_POST['BOOKING_PSENDER'];
	$BOOKING_PCONTACTNUMBER = $_POST['BOOKING_PCONTACTNUMBER'];
	$BOOKING_PCITY = $_POST['BOOKING_PCITY'];
	$BOOKING_PADDRESS = $_POST['BOOKING_PADDRESS'];
	$BOOKING_PLANDMARK = $_POST['BOOKING_PLANDMARK'];
	$BOOKING_DCONSIGNEE = $_POST['BOOKING_DCONSIGNEE'];
	$BOOKING_DCONTACTNUMBER = $_POST['BOOKING_DCONTACTNUMBER'];
	$BOOKING_DCITY = $_POST['BOOKING_DCITY'];
	$BOOKING_DADDRESS = $_POST['BOOKING_DADDRESS'];
	$BOOKING_DLANDMARK = $_POST['BOOKING_DLANDMARK'];
	$BOOKING_TYPE = $_POST['BOOKING_TYPE'];
	$BOOKING_WEIGHT = $_POST['BOOKING_WEIGHT'];
	$BOOKING_SIZE = $_POST['BOOKING_SIZE'];
	$BOOKING_REMARKS = $_POST['BOOKING_REMARKS'];
	$BOOKING_INSURANCE = $_POST['BOOKING_INSURANCE'];
	$BOOKING_PRICE = $_POST['BOOKING_PRICE'];
	$BOOKING_BILLNUMBER = $_POST['BOOKING_BILLNUMBER'];
	$BOOKING_PDATE = $_POST['BOOKING_PDATE'];
	$BOOKING_PTIME = $_POST['BOOKING_PTIME'];
	$BOOKING_PBY = $_POST['BOOKING_PBY'];
	$BOOKING_CODPAYMENT = $_POST['BOOKING_CODPAYMENT'];
	$BOOKING_DELIVERYDATE = $_POST['BOOKING_DELIVERYDATE'];
	$BOOKING_IDATE = $_POST['BOOKING_IDATE'];
	$BOOKING_ITIME = $_POST['BOOKING_ITIME'];
	$BOOKING_DDATE = $_POST['BOOKING_DDATE'];
	$BOOKING_DTIME = $_POST['BOOKING_DTIME'];
	$BOOKING_RBY = $_POST['BOOKING_RBY'];
	$BOOKING_DESCRIPTION = $_POST['BOOKING_DESCRIPTION'];
		$BOOKING_PAYMENT = $_POST['BOOKING_PAYMENT'];
$sql = "UPDATE booking SET BOOKING_PSENDER = '$BOOKING_PSENDER', BOOKING_PCONTACTNUMBER = '$BOOKING_PCONTACTNUMBER', BOOKING_PCITY = '$BOOKING_PCITY', BOOKING_PADDRESS = '$BOOKING_PADDRESS', BOOKING_PLANDMARK = '$BOOKING_PLANDMARK', BOOKING_DCONSIGNEE = '$BOOKING_DCONSIGNEE', BOOKING_DCONTACTNUMBER = '$BOOKING_DCONTACTNUMBER', BOOKING_DCITY = '$BOOKING_DCITY', BOOKING_DADDRESS = '$BOOKING_DADDRESS', BOOKING_DLANDMARK = '$BOOKING_DLANDMARK', BOOKING_TYPE = '$BOOKING_TYPE', BOOKING_WEIGHT = '$BOOKING_WEIGHT', BOOKING_SIZE = '$BOOKING_SIZE', BOOKING_REMARKS = '$BOOKING_REMARKS', BOOKING_INSURANCE = '$BOOKING_INSURANCE', BOOKING_PRICE = '$BOOKING_PRICE', BOOKING_BILLNUMBER = '$BOOKING_BILLNUMBER', BOOKING_PDATE = '$BOOKING_PDATE', BOOKING_PTIME = '$BOOKING_PTIME', BOOKING_PBY = '$BOOKING_PBY', BOOKING_CODPAYMENT = '$BOOKING_CODPAYMENT', BOOKING_DELIVERYDATE = '$BOOKING_DELIVERYDATE',BOOKING_IDATE= '$BOOKING_IDATE', BOOKING_ITIME = '$BOOKING_ITIME', BOOKING_DDATE = '$BOOKING_DDATE', BOOKING_DTIME = '$BOOKING_DTIME', BOOKING_RBY = '$BOOKING_RBY', BOOKING_PAYMENT = '$BOOKING_PAYMENT', BOOKING_DESCRIPTION='$BOOKING_DESCRIPTION'  WHERE BOOKING_ID = '$BOOKING_ID'";
	$query = $link->query($sql);

	if($query === TRUE) {			
		$validator['success'] = true;
		$validator['messages'] = "Successfully Modified Information";		
	} else {		
		$validator['success'] = false;
		$validator['messages'] = "Error while adding the member information";
	}

	// close the database connection
	$link->close();

	echo json_encode($validator);

}